// Expressões regulares

// Utilizando replace com regex

var text = 'Manuel Marques de Sousa, Conde de Porto Alegre (Rio Grande, 13 de junho de 1804 – Rio de Janeiro, 18 de julho de 1875), apelidado de "O Centauro de Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e de tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década de 1820 no esforço brasileiro para manter a Cisplatina como parte de seu território, primeiro durante a independência do Brasil e depois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação independente do Uruguai.';

text.replace('de', 'DE'); //"Manuel Marques DE Sousa, Conde de Porto Alegre (Rio Grande, 13 de junho de 1804 – Rio de Janeiro, 18 de julho de 1875), apelidado de "O Centauro de Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e de tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década de 1820 no esforço brasileiro para manter a Cisplatina como parte de seu território, primeiro durante a independência do Brasil e depois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação independente do Uruguai."

text.replace(/de/, 'DE'); //"Manuel Marques DE Sousa, Conde de Porto Alegre (Rio Grande, 13 de junho de 1804 – Rio de Janeiro, 18 de julho de 1875), apelidado de "O Centauro de Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e de tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década de 1820 no esforço brasileiro para manter a Cisplatina como parte de seu território, primeiro durante a independência do Brasil e depois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação independente do Uruguai."

text.replace(/de/g, 'DE'); //"Manuel Marques DE Sousa, ConDE DE Porto Alegre (Rio GranDE, 13 DE junho DE 1804 – Rio DE Janeiro, 18 DE julho DE 1875), apelidado DE "O Centauro DE Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e DE tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década DE 1820 no esforço brasileiro para manter a Cisplatina como parte DE seu território, primeiro durante a inDEpendência do Brasil e DEpois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação inDEpenDEnte do Uruguai."

text.replace(/de/g, '--DE'); //"Manuel Marques --DE Sousa, Con--DE --DE Porto Alegre (Rio Gran--DE, 13 --DE junho --DE 1804 – Rio --DE Janeiro, 18 --DE julho --DE 1875), apelidado --DE "O Centauro --DE Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e --DE tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década --DE 1820 no esforço brasileiro para manter a Cisplatina como parte --DE seu território, primeiro durante a in--DEpendência do Brasil e --DEpois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação in--DEpen--DEnte do Uruguai."

text.replace(/(de)/g, '$1'); //"Manuel Marques de Sousa, Conde de Porto Alegre (Rio Grande, 13 de junho de 1804 – Rio de Janeiro, 18 de julho de 1875), apelidado de "O Centauro de Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e de tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década de 1820 no esforço brasileiro para manter a Cisplatina como parte de seu território, primeiro durante a independência do Brasil e depois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação independente do Uruguai."

text.replace(/(de)/g, '--$1--'); //"Manuel Marques --de-- Sousa, Con--de-- --de-- Porto Alegre (Rio Gran--de--, 13 --de-- junho --de-- 1804 – Rio --de-- Janeiro, 18 --de-- julho --de-- 1875), apelidado --de-- "O Centauro --de-- Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e --de-- tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década --de-- 1820 no esforço brasileiro para manter a Cisplatina como parte --de-- seu território, primeiro durante a in--de--pendência do Brasil e --de--pois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação in--de--pen--de--nte do Uruguai."

text.replace(/(d)(e)/g, 'DE'); //"Manuel Marques DE Sousa, ConDE DE Porto Alegre (Rio GranDE, 13 DE junho DE 1804 – Rio DE Janeiro, 18 DE julho DE 1875), apelidado DE "O Centauro DE Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e DE tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década DE 1820 no esforço brasileiro para manter a Cisplatina como parte DE seu território, primeiro durante a inDEpendência do Brasil e DEpois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação inDEpenDEnte do Uruguai."

text.replace(/(d)(e)/g, '$1$1'); //"Manuel Marques dd Sousa, Condd dd Porto Alegre (Rio Grandd, 13 dd junho dd 1804 – Rio dd Janeiro, 18 dd julho dd 1875), apelidado dd "O Centauro dd Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e dd tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década dd 1820 no esforço brasileiro para manter a Cisplatina como parte dd seu território, primeiro durante a inddpendência do Brasil e ddpois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação inddpenddnte do Uruguai."

text.replace(/(d)(e)/g, '--$2'); //"Manuel Marques --e Sousa, Con--e --e Porto Alegre (Rio Gran--e, 13 --e junho --e 1804 – Rio --e Janeiro, 18 --e julho --e 1875), apelidado --e "O Centauro --e Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e --e tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década --e 1820 no esforço brasileiro para manter a Cisplatina como parte --e seu território, primeiro durante a in--ependência do Brasil e --epois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação in--epen--ente do Uruguai."

text.replace(/(d)(e)/g, '--$&'); //"Manuel Marques --de Sousa, Con--de --de Porto Alegre (Rio Gran--de, 13 --de junho --de 1804 – Rio --de Janeiro, 18 --de julho --de 1875), apelidado --de "O Centauro --de Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e --de tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década --de 1820 no esforço brasileiro para manter a Cisplatina como parte --de seu território, primeiro durante a in--dependência do Brasil e --depois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação in--depen--dente do Uruguai."

text.replace(/(d)(e)/g, '$&'.toUpperCase()); //"Manuel Marques de Sousa, Conde de Porto Alegre (Rio Grande, 13 de junho de 1804 – Rio de Janeiro, 18 de julho de 1875), apelidado de "O Centauro de Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e de tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década de 1820 no esforço brasileiro para manter a Cisplatina como parte de seu território, primeiro durante a independência do Brasil e depois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação independente do Uruguai."

text.replace(/(d)(e)/g, function(){
	console.log(arguments);
}); //Arguments(5) ["de", "d", "e"]  "Manuel Marques undefined Sousa, Conundefined undefined Porto Alegre (Rio Granundefined, 13 undefined junho undefined 1804 – Rio undefined Janeiro, 18 undefined julho undefined 1875), apelidado undefined "O Centauro undefined Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e undefined tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década undefined 1820 no esforço brasileiro para manter a Cisplatina como parte undefined seu território, primeiro durante a inundefinedpendência do Brasil e undefinedpois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação inundefinedpenundefinednte do Uruguai."

text.replace(/(d)(e)/g, function(capturaTotal, d, e){
	return (d + e).toUpperCase();
}); //"Manuel Marques DE Sousa, ConDE DE Porto Alegre (Rio GranDE, 13 DE junho DE 1804 – Rio DE Janeiro, 18 DE julho DE 1875), apelidado DE "O Centauro DE Luvas",[nota 1] foi um militar, político, abolicionista e monarquista brasileiro. Ele nasceu em uma família rica e DE tradição militar, entrando no exército em 1817 quando ainda era criança. Sua iniciação militar ocorreu na Guerra contra Artigas, que teve seu território anexado e se tornou em 1821 a província brasileira da Cisplatina. Ele ficou envolvido durante boa parte da década DE 1820 no esforço brasileiro para manter a Cisplatina como parte DE seu território, primeiro durante a inDEpendência do Brasil e DEpois na Guerra da Cisplatina. No final a província conseguiu se separar e se tornou a nação inDEpenDEnte do Uruguai."

'Junior'.replace(/(\w)/g, function(capturaTotal, letra) {
	return letra.toUpperCase();
}); //"JUNIOR"

'Junior'.replace(/(\w)(\w)/g, function(capturaTotal, letra1, letra2) {
	return letra1.toUpperCase() + letra2.toLowerCase();
}); //"JuNiOr"